athlete_id: willer01
name: Mr. Willer
strava_id: ""
garmin_id: ""
ftp_watts: 280
weight_kg: 70.0
birth_year: 1985
gender: Male
fitness_level: Intermediate
available_hours: 9
max_hr: 182
resting_hr: 55
lthr: 154
training_goal: Build cycling fitness for sub 5 hr century ride. I Like to ride 100+ mi a week, I am a busy professional and a rock climber.
injury_history: None