- event_name: Century
  event_date: "2026-07-20"
  priority: A
  event_type: Solo Ride
  target: "Finish under 5h"
  notes: "Main season goal"

- event_name: Fall Adventure
  event_date: "2026-09-15"
  priority: B
  event_type: Adventure
  target: "Complete 150km route"
  notes: "Test endurance"

- event_name: Ride 4000 mi this year
  event_date: "2026-09-15"
  priority: A
  event_type: Year Long
  target: "Complete goal of 4000 mi this year"
  notes: "Test endurance"